export const IMAGE_ALLOW_TYPE = 'image/jpeg, image/png';
export const FILE_ALLOW_TYPE = '.csv,.xlsx';
export const MAX_SIZE_IMAGE = 20971520; // 20mb
export const MAX_SIZE_AVATAR_IMAGE = 5000000;
export const MIN_SIZE_IMAGE = 10240; // 10kb
export const MAX_DIMENSION = 4096;
export const MIN_DIMENSION_WIDTH = 880;
export const MIN_DIMENSION_HEIGHT = 600;
export const MAX_NUMBER_PHOTOS = 500;
